name = "ExaModelsPEtab"
uuid = "449f6601-3844-48f4-990d-d57d890903df"
version = "1.0.0-DEV"
authors = ["Joseph Choi <jsphchoi@mit.edu> and contributors"]

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
